[package]
name = "awbw-replay"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2.workspace = true
phpserz.workspace = true
rawzip.workspace = true
serde.workspace = true
serde_json.workspace = true
