import * as stylex from "@stylexjs/stylex";

export const media = stylex.defineConsts({
  narrow: "@media (max-width: 860px)",
  compact: "@media (max-width: 640px)",
});

export const tokens = stylex.defineVars({
  fontBody: "",
  fontPixel: "",
  pageBg: "",
  pageGrid: "",
  pageGlow: "",
  chromeBg: "",
  chromeBgElevated: "",
  chromeBgLight: "",
  chromeBorder: "",
  chromeBorderSoft: "",
  panelBg: "",
  panelRaised: "",
  panelInset: "",
  panelTint: "",
  hazardYellow: "",
  hazardYellowDeep: "",
  hazardStripe: "",
  hazardInk: "",
  strokeHeavy: "",
  strokeBase: "",
  strokeLight: "",
  lineStrong: "",
  lineSoft: "",
  inkStrong: "",
  ink: "",
  inkSoft: "",
  inkMuted: "",
  onDarkStrong: "",
  onDark: "",
  onDarkMuted: "",
  brand: "",
  brandHover: "",
  brandSoft: "",
  factionOs: "",
  factionBm: "",
  factionGe: "",
  factionYc: "",
  factionBh: "",
  success: "",
  successHover: "",
  danger: "",
  dangerHover: "",
  info: "",
  infoHover: "",
  focusRing: "",
  radius1: "",
  radius2: "",
  radius3: "",
  radiusRound: "",
  space0: "",
  space1: "",
  space2: "",
  space3: "",
  space4: "",
  space5: "",
  space6: "",
  space8: "",
  space10: "",
  space12: "",
  space16: "",
  textXs: "",
  textSm: "",
  textBase: "",
  textLg: "",
  textXl: "",
  text2xl: "",
  displaySm: "",
  displayMd: "",
  leadingPixel: "",
  leadingBody: "",
  trackingPixel: "",
  trackingWide: "",
  highlightInset: "",
  highlightInsetChrome: "",
  shadowHardSm: "",
  shadowHardMd: "",
  shadowHardLg: "",
  pressOffsetSm: "",
  pressOffsetMd: "",
  shadowLine: "",
  shadowLift: "",
  transitionFast: "",
  transitionBase: "",
  navHeight: "",
  maxWidth: "",
  maxWidthWide: "",
});

export const appTheme = stylex.createTheme(tokens, {
  fontBody: '"Nunito", sans-serif',
  fontPixel: '"Press Start 2P", monospace',
  pageBg: "#4a3418",
  pageGrid: "rgba(40, 28, 8, 0.18)",
  pageGlow: "rgba(220, 168, 60, 0.22)",
  chromeBg: "#8a6232",
  chromeBgElevated: "#9a7040",
  chromeBgLight: "#fff5dc",
  chromeBorder: "rgba(255, 216, 148, 0.52)",
  chromeBorderSoft: "rgba(255, 216, 148, 0.26)",
  panelBg: "#f8edc9",
  panelRaised: "#fff6dd",
  panelInset: "#ddc892",
  panelTint: "rgba(255, 255, 255, 0.24)",
  hazardYellow: "#f3d51b",
  hazardYellowDeep: "#c3a100",
  hazardStripe: "repeating-linear-gradient(135deg, #f3d51b 0 16px, #151008 16px 32px)",
  hazardInk: "#1f1b17",
  strokeHeavy: "#120d08",
  strokeBase: "#5a3f1e",
  strokeLight: "#fff1c5",
  lineStrong: "#37291f",
  lineSoft: "#8e744c",
  inkStrong: "#1d2532",
  ink: "#2a3544",
  inkSoft: "#49505d",
  inkMuted: "#666b74",
  onDarkStrong: "#fff5de",
  onDark: "#f1ddb5",
  onDarkMuted: "#d2b789",
  brand: "#e76426",
  brandHover: "#c4480f",
  brandSoft: "#ffd09d",
  factionOs: "#ff4f4e",
  factionBm: "#466efe",
  factionGe: "#3dc22d",
  factionYc: "#9f8f00",
  factionBh: "#74598a",
  success: "#1a9e3f",
  successHover: "#0f7a2e",
  danger: "#d42b1e",
  dangerHover: "#a01d13",
  info: "#1e7ac8",
  infoHover: "#145899",
  focusRing: "#e76426",
  radius1: "3px",
  radius2: "8px",
  radius3: "12px",
  radiusRound: "999px",
  space0: "0px",
  space1: "4px",
  space2: "8px",
  space3: "12px",
  space4: "16px",
  space5: "20px",
  space6: "24px",
  space8: "32px",
  space10: "40px",
  space12: "48px",
  space16: "64px",
  textXs: "12px",
  textSm: "14px",
  textBase: "16px",
  textLg: "18px",
  textXl: "20px",
  text2xl: "24px",
  displaySm: "clamp(18px, 2.2vw, 22px)",
  displayMd: "clamp(22px, 3.5vw, 40px)",
  leadingPixel: "1.6",
  leadingBody: "1.55",
  trackingPixel: "0.08em",
  trackingWide: "0.14em",
  highlightInset:
    "inset 0 0 0 2px rgba(255, 246, 210, 0.9), inset 0 3px 0 rgba(255, 255, 255, 0.65)",
  highlightInsetChrome:
    "inset 0 0 0 1px rgba(255, 221, 168, 0.24), inset 0 2px 0 rgba(255, 238, 205, 0.16)",
  shadowHardSm: "2px 2px 0 #000",
  shadowHardMd: "4px 4px 0 #000",
  shadowHardLg: "6px 6px 0 #000",
  pressOffsetSm: "2px",
  pressOffsetMd: "4px",
  shadowLine: "inset 0 0 0 2px rgba(255, 246, 210, 0.9), inset 0 3px 0 rgba(255, 255, 255, 0.65)",
  shadowLift: "6px 6px 0 #000",
  transitionFast: "120ms ease",
  transitionBase: "180ms ease",
  navHeight: "68px",
  maxWidth: "1380px",
  maxWidthWide: "1560px",
});

export const cursorBlink = stylex.keyframes({
  "0%, 49%": { opacity: 1 },
  "50%, 100%": { opacity: 0.25 },
});

export const riseIn = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(18px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

export const rootStyles = stylex.create({
  html: {
    backgroundColor: tokens.pageBg,
    color: tokens.onDark,
    fontFamily: tokens.fontBody,
    fontSynthesis: "none",
    MozOsxFontSmoothing: "grayscale",
    WebkitFontSmoothing: "antialiased",
    textRendering: "optimizeLegibility",
  },
  body: {
    margin: 0,
    minHeight: "100vh",
    minWidth: 320,
    position: "relative",
    backgroundColor: tokens.pageBg,
    backgroundImage: [
      `radial-gradient(circle at 50% 0%, ${tokens.pageGlow}, transparent 34%)`,
      "linear-gradient(rgba(255, 236, 196, 0.02), rgba(255, 236, 196, 0.02))",
      `linear-gradient(${tokens.pageGrid} 1px, transparent 1px)`,
      `linear-gradient(90deg, ${tokens.pageGrid} 1px, transparent 1px)`,
    ].join(", "),
    backgroundSize: "auto, auto, 48px 48px, 48px 48px",
    color: tokens.onDark,
  },
  appRoot: {
    isolation: "isolate",
    minHeight: "100vh",
  },
  shell: {
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
  },
  link: {
    color: {
      default: tokens.brand,
      ":hover": tokens.brandHover,
    },
    textDecoration: "none",
    transitionDuration: tokens.transitionFast,
    transitionProperty: "color",
  },
  code: {
    fontFamily: tokens.fontPixel,
    fontSize: 10,
    letterSpacing: "0.06em",
  },
});

export const spacingScale = {
  0: tokens.space0,
  1: tokens.space1,
  2: tokens.space2,
  3: tokens.space3,
  4: tokens.space4,
  5: tokens.space5,
  6: tokens.space6,
  8: tokens.space8,
  10: tokens.space10,
  12: tokens.space12,
  16: tokens.space16,
} as const;

export const typeScale = {
  xs: tokens.textXs,
  sm: tokens.textSm,
  base: tokens.textBase,
  lg: tokens.textLg,
  xl: tokens.textXl,
  "2xl": tokens.text2xl,
  displaySm: tokens.displaySm,
  displayMd: tokens.displayMd,
} as const;

export const componentScales = {
  gap: {
    xs: tokens.space2,
    sm: tokens.space3,
    md: tokens.space4,
    lg: tokens.space6,
    xl: tokens.space8,
  },
  text: {
    sm: tokens.textSm,
    md: tokens.textBase,
    lg: tokens.textLg,
  },
  heading: {
    md: tokens.textXs,
    lg: tokens.displaySm,
    display: tokens.displayMd,
  },
} as const;
