[package]
name = "awbrn-server"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
awbrn-ai = { path = "../awbrn-ai" }
awbrn-game = { path = "../awbrn-game", features = ["typescript"] }
awbrn-image = { path = "../awbrn-image" }
awbrn-map = { path = "../awbrn-map" }
awbrn-protocol = { path = "../awbrn-protocol" }
awbrn-types = { path = "../awbrn-types" }
awvm = { path = "../awvm", features = ["typescript"] }
serde.workspace = true
serde-wasm-bindgen.workspace = true
serde_json.workspace = true
tracing.workspace = true
tsify.workspace = true
wasm-bindgen.workspace = true

[dev-dependencies]
awbrn-ai = { path = "../awbrn-ai" }
insta.workspace = true
