/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/awbrnTheme.ts
 * Command: astryx theme build src/themes/awbrnTheme.ts
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

// Generated by astryx theme build
export {};

declare module "@astryxdesign/core/Badge" {
  interface BadgeVariantMap {
    gray: true;
  }
}

declare module "@astryxdesign/core/Token" {
  interface TokenColorMap {
    "faction-os": true;
    "faction-bm": true;
    "faction-ge": true;
    "faction-yc": true;
    "faction-bh": true;
    "faction-rf": true;
    "faction-gs": true;
    "faction-bd": true;
    "faction-ab": true;
    "faction-js": true;
    "faction-ci": true;
    "faction-pc": true;
    "faction-tg": true;
    "faction-pl": true;
    "faction-ar": true;
    "faction-wn": true;
    "faction-aa": true;
    "faction-ne": true;
    "faction-sc": true;
    "faction-uw": true;
  }
}
