/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/awbrnTheme.ts
 * Command: astryx theme build src/themes/awbrnTheme.ts
 * Generated: 2026-08-05T23:35:27.730Z
 */

/// <reference path="./awbrn.variants.d.ts" />
import type { DefinedTheme } from "@astryxdesign/core/theme";
export declare const awbrnTheme: DefinedTheme;
