[package]
name = "awbrn-game"
version = "0.1.0"
edition = "2024"

[dependencies]
awbrn-types = { path = "../awbrn-types", features = ["bevy"] }
awbrn-map = { path = "../awbrn-map", features = ["bevy"] }
awbw-replay = { path = "../awbw-replay" }
awvm = { path = "../awvm" }
bevy = { workspace = true, features = ["std", "bevy_log", "bevy_world_serialization"] }
indexmap.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true
awvm-awbw = { path = "../awvm-awbw" }
awbw-replay = { path = "../awbw-replay" }
serde_json.workspace = true
