// This file is generated by unit_animation.py --rust
fn get_animation_data(unit: Unit) -> (u16, UnitAnimationData) {
match unit {
    Unit::Infantry => (0, UnitAnimationData::new(
        &[160, 160, 320, 160],
        &[120, 120, 120, 120],
        &[120, 120, 120, 120],
        &[120, 120, 120, 120],
    )),
    Unit::Mech => (16, UnitAnimationData::new(
        &[480, 320],
        &[120, 120, 120, 120],
        &[120, 120, 120, 120],
        &[120, 120, 120, 120],
    )),
    Unit::MdTank => (30, UnitAnimationData::new(
        &[160, 160, 320, 160],
        &[80, 80, 80],
        &[80, 80, 80],
        &[80, 80, 80],
    )),
    Unit::Tank => (43, UnitAnimationData::new(
        &[160, 160, 320, 160],
        &[80, 80, 80],
        &[80, 80, 80],
        &[80, 80, 80],
    )),
    Unit::Recon => (56, UnitAnimationData::new(
        &[160, 160, 320, 160],
        &[80, 80, 80],
        &[80, 80, 80],
        &[80, 80, 80],
    )),
    Unit::APC => (69, UnitAnimationData::new(
        &[160, 160, 320, 160],
        &[80, 80, 80],
        &[80, 80, 80],
        &[80, 80, 80],
    )),
    Unit::Artillery => (82, UnitAnimationData::new(
        &[160, 160, 320, 160],
        &[80, 80, 80],
        &[80, 80, 80],
        &[80, 80, 80],
    )),
    Unit::Rocket => (95, UnitAnimationData::new(
        &[320, 480],
        &[80, 80, 80],
        &[80, 80, 80],
        &[80, 80, 80],
    )),
    Unit::AntiAir => (106, UnitAnimationData::new(
        &[160, 160, 320, 160],
        &[80, 80, 80],
        &[80, 80, 80],
        &[80, 80, 80],
    )),
    Unit::Missile => (119, UnitAnimationData::new(
        &[480, 320],
        &[80, 80, 80],
        &[80, 80, 80],
        &[80, 80, 80],
    )),
    Unit::Fighter => (130, UnitAnimationData::new(
        &[320, 480],
        &[120, 120, 120],
        &[120, 120, 120],
        &[120, 120, 120],
    )),
    Unit::Bomber => (141, UnitAnimationData::new(
        &[480, 320],
        &[120, 120, 120],
        &[120, 120, 120],
        &[120, 120, 120],
    )),
    Unit::BCopter => (152, UnitAnimationData::new(
        &[160, 160, 320, 160],
        &[30, 30],
        &[30, 30],
        &[30, 30],
    )),
    Unit::TCopter => (162, UnitAnimationData::new(
        &[160, 160, 320, 160],
        &[30, 30],
        &[30, 30],
        &[30, 30],
    )),
    Unit::Battleship => (172, UnitAnimationData::new(
        &[320, 480],
        &[480, 160],
        &[480, 160],
        &[480, 160],
    )),
    Unit::Cruiser => (180, UnitAnimationData::new(
        &[480, 320],
        &[480, 160],
        &[480, 160],
        &[160, 480],
    )),
    Unit::Lander => (188, UnitAnimationData::new(
        &[320, 480],
        &[480, 160],
        &[480, 160],
        &[480, 160],
    )),
    Unit::Sub => (196, UnitAnimationData::new(
        &[160, 160, 320, 160],
        &[480, 160],
        &[480, 160],
        &[480, 160],
    )),
    Unit::BlackBoat => (206, UnitAnimationData::new(
        &[320, 160, 160, 160],
        &[480, 160],
        &[480, 160],
        &[480, 160],
    )),
    Unit::Carrier => (216, UnitAnimationData::new(
        &[320, 480],
        &[480, 160],
        &[480, 160],
        &[480, 160],
    )),
    Unit::Stealth => (224, UnitAnimationData::new(
        &[480, 320],
        &[120, 120, 120],
        &[120, 120, 120],
        &[120, 120, 120],
    )),
    Unit::NeoTank => (235, UnitAnimationData::new(
        &[160, 160, 320, 160],
        &[80, 80, 80],
        &[80, 80, 80],
        &[80, 80, 80],
    )),
    Unit::PipeRunner => (248, UnitAnimationData::new(
        &[480, 320],
        &[80, 80, 80],
        &[80, 80, 80],
        &[80, 80, 80],
    )),
    Unit::BlackBomb => (259, UnitAnimationData::new(
        &[220, 220, 220, 220],
        &[120, 120, 120],
        &[120, 120, 120],
        &[120, 120, 120],
    )),
    Unit::MegaTank => (272, UnitAnimationData::new(
        &[160, 160, 320, 160],
        &[80, 80, 80],
        &[80, 80, 80],
        &[80, 80, 80],
    )),
}
}
impl UnitAnimationData {
pub const TOTAL_FRAMES: usize = 285;
}
