[alias]
xtask-assets = "run --package xtask-assets --"
xtask-ruleset = "run --package xtask-ruleset --"

[target.wasm32-unknown-unknown]
rustflags = [
    "--cfg",
    "getrandom_backend=\"wasm_js\"",
]
