[package]
name = "bench"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[lib]
bench = false

[dependencies]
awbrn-ai = { path = "../awbrn-ai" }
awbrn-map = { path = "../awbrn-map" }
awbrn-server = { path = "../awbrn-server" }
awbrn-types = { path = "../awbrn-types" }
awbw-replay = { path = "../awbw-replay" }
awvm = { path = "../awvm" }
criterion = { workspace = true }
serde_json.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
criterion = { workspace = true, default-features = true }
gungraun = { workspace = true }

[[bench]]
name = "awbrn-bench-criterion"
harness = false
path = "src/criterion_main.rs"

[[bench]]
name = "awbrn-bench-gungraun"
harness = false
test = false
path = "src/gungraun_main.rs"
