[package]
name = "awbrn-map"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
bevy = ["dep:bevy"]

[dependencies]
awbrn-types.path = "../awbrn-types"
awvm.path = "../awvm"
bevy = { workspace = true, optional = true }
jiff.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
insta.workspace = true
rstest.workspace = true
