[package]
name = "awbrn-image"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
name = "awbrn-image"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
awbrn-content = { path = "../awbrn-content" }
awbrn-map = { path = "../awbrn-map" }
awbrn-types = { path = "../awbrn-types" }
awvm = { path = "../awvm" }
image.workspace = true
png.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
highway.workspace = true
