import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const CANONICAL_CODES = [
  "Backquote",
  "Backslash",
  "BracketLeft",
  "BracketRight",
  "Comma",
  "Digit0",
  "Digit1",
  "Digit2",
  "Digit3",
  "Digit4",
  "Digit5",
  "Digit6",
  "Digit7",
  "Digit8",
  "Digit9",
  "Equal",
  "IntlBackslash",
  "IntlRo",
  "IntlYen",
  "KeyA",
  "KeyB",
  "KeyC",
  "KeyD",
  "KeyE",
  "KeyF",
  "KeyG",
  "KeyH",
  "KeyI",
  "KeyJ",
  "KeyK",
  "KeyL",
  "KeyM",
  "KeyN",
  "KeyO",
  "KeyP",
  "KeyQ",
  "KeyR",
  "KeyS",
  "KeyT",
  "KeyU",
  "KeyV",
  "KeyW",
  "KeyX",
  "KeyY",
  "KeyZ",
  "Minus",
  "Period",
  "Quote",
  "Semicolon",
  "Slash",
  "AltLeft",
  "AltRight",
  "Backspace",
  "CapsLock",
  "ContextMenu",
  "ControlLeft",
  "ControlRight",
  "Enter",
  "MetaLeft",
  "MetaRight",
  "ShiftLeft",
  "ShiftRight",
  "Space",
  "Tab",
  "Convert",
  "KanaMode",
  "Lang1",
  "Lang2",
  "Lang3",
  "Lang4",
  "Lang5",
  "NonConvert",
  "Delete",
  "End",
  "Help",
  "Home",
  "Insert",
  "PageDown",
  "PageUp",
  "ArrowDown",
  "ArrowLeft",
  "ArrowRight",
  "ArrowUp",
  "NumLock",
  "Numpad0",
  "Numpad1",
  "Numpad2",
  "Numpad3",
  "Numpad4",
  "Numpad5",
  "Numpad6",
  "Numpad7",
  "Numpad8",
  "Numpad9",
  "NumpadAdd",
  "NumpadBackspace",
  "NumpadClear",
  "NumpadClearEntry",
  "NumpadComma",
  "NumpadDecimal",
  "NumpadDivide",
  "NumpadEnter",
  "NumpadEqual",
  "NumpadHash",
  "NumpadMemoryAdd",
  "NumpadMemoryClear",
  "NumpadMemoryRecall",
  "NumpadMemoryStore",
  "NumpadMemorySubtract",
  "NumpadMultiply",
  "NumpadParenLeft",
  "NumpadParenRight",
  "NumpadStar",
  "NumpadSubtract",
  "Escape",
  "Fn",
  "FnLock",
  "PrintScreen",
  "ScrollLock",
  "Pause",
  "BrowserBack",
  "BrowserFavorites",
  "BrowserForward",
  "BrowserHome",
  "BrowserRefresh",
  "BrowserSearch",
  "BrowserStop",
  "Eject",
  "LaunchApp1",
  "LaunchApp2",
  "LaunchMail",
  "MediaPlayPause",
  "MediaSelect",
  "MediaStop",
  "MediaTrackNext",
  "MediaTrackPrevious",
  "Power",
  "Sleep",
  "AudioVolumeDown",
  "AudioVolumeMute",
  "AudioVolumeUp",
  "WakeUp",
  "Meta",
  "Hyper",
  "Turbo",
  "Abort",
  "Resume",
  "Suspend",
  "Again",
  "Copy",
  "Cut",
  "Find",
  "Open",
  "Paste",
  "Props",
  "Select",
  "Undo",
  "Hiragana",
  "Katakana",
  "F1",
  "F2",
  "F3",
  "F4",
  "F5",
  "F6",
  "F7",
  "F8",
  "F9",
  "F10",
  "F11",
  "F12",
  "F13",
  "F14",
  "F15",
  "F16",
  "F17",
  "F18",
  "F19",
  "F20",
  "F21",
  "F22",
  "F23",
  "F24",
  "F25",
  "F26",
  "F27",
  "F28",
  "F29",
  "F30",
  "F31",
  "F32",
  "F33",
  "F34",
  "F35",
] as const;

const CODE_ALIASES: Record<string, (typeof CANONICAL_CODES)[number]> = {
  OSLeft: "MetaLeft",
  OSRight: "MetaRight",
  SuperLeft: "MetaLeft",
  SuperRight: "MetaRight",
};

const RUST_KEY_CODE_VARIANTS: Partial<Record<(typeof CANONICAL_CODES)[number], string>> = {
  MetaLeft: "SuperLeft",
  MetaRight: "SuperRight",
};

const tsOutputPath = resolve("web/src/canvas_courier/key_codes.generated.ts");
const rustOutputPath = resolve("crates/awbrn-wasm/src/web_key_code_generated.rs");

const wireValueByCode = new Map<string, number>(
  CANONICAL_CODES.map((code, index) => [code, index + 1]),
);

function ensureParentDirectory(path: string) {
  mkdirSync(dirname(path), { recursive: true });
}

function renderTsFile() {
  const objectMembers = CANONICAL_CODES.map((code) => `  ${code}: ${wireValueByCode.get(code)!},`);
  const mappings = CANONICAL_CODES.map((code) => `  ${JSON.stringify(code)}: WebKeyCode.${code},`);
  const aliasMappings = Object.entries(CODE_ALIASES).map(
    ([alias, canonical]) => `  ${JSON.stringify(alias)}: WebKeyCode.${canonical},`,
  );

  return `// Generated by scripts/generate-web-key-codes.ts. Do not edit by hand.

export const WebKeyCode = {
  Unknown: 0,
${objectMembers.join("\n")}
} as const;

export type WebKeyCode = (typeof WebKeyCode)[keyof typeof WebKeyCode];

export const WEB_KEY_CODE_BY_EVENT_CODE: Readonly<Record<string, WebKeyCode>> = {
${mappings.join("\n")}
${aliasMappings.join("\n")}
};

export function encodeWebKeyCode(code: string): WebKeyCode {
  return WEB_KEY_CODE_BY_EVENT_CODE[code] ?? WebKeyCode.Unknown;
}
`;
}

function renderRustFile() {
  const enumMembers = CANONICAL_CODES.map((code) => `    ${code} = ${wireValueByCode.get(code)!},`);
  const decodeArms = CANONICAL_CODES.map(
    (code) => `            ${wireValueByCode.get(code)!} => Self::${code},`,
  );
  const toBevyArms = CANONICAL_CODES.map((code) => {
    const bevyVariant = RUST_KEY_CODE_VARIANTS[code] ?? code;
    return `            Self::${code} => KeyCode::${bevyVariant},`;
  });

  return `// Generated by scripts/generate-web-key-codes.ts. Do not edit by hand.

use bevy::input::keyboard::{KeyCode, NativeKeyCode};

#[repr(u16)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum WebKeyCode {
    Unknown = 0,
${enumMembers.join("\n")}
}

impl WebKeyCode {
    pub fn from_wire_code(value: u16) -> Self {
        match value {
${decodeArms.join("\n")}
            _ => Self::Unknown,
        }
    }

    pub fn to_bevy_key_code(self) -> KeyCode {
        match self {
            Self::Unknown => KeyCode::Unidentified(NativeKeyCode::Unidentified),
${toBevyArms.join("\n")}
        }
    }
}
`;
}

ensureParentDirectory(tsOutputPath);
ensureParentDirectory(rustOutputPath);

writeFileSync(tsOutputPath, renderTsFile());
writeFileSync(rustOutputPath, renderRustFile());
