/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameNewRouteImport } from './routes/game/new'
import { Route as ApiAwbwUserUserIdRouteImport } from './routes/api/awbw/user.$userId'
import { Route as ApiAwbwMapMapIdRouteImport } from './routes/api/awbw/map.$mapId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameNewRoute = GameNewRouteImport.update({
  id: '/game/new',
  path: '/game/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAwbwUserUserIdRoute = ApiAwbwUserUserIdRouteImport.update({
  id: '/api/awbw/user/$userId',
  path: '/api/awbw/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAwbwMapMapIdRoute = ApiAwbwMapMapIdRouteImport.update({
  id: '/api/awbw/map/$mapId',
  path: '/api/awbw/map/$mapId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/game/new': typeof GameNewRoute
  '/api/awbw/map/$mapId': typeof ApiAwbwMapMapIdRoute
  '/api/awbw/user/$userId': typeof ApiAwbwUserUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/game/new': typeof GameNewRoute
  '/api/awbw/map/$mapId': typeof ApiAwbwMapMapIdRoute
  '/api/awbw/user/$userId': typeof ApiAwbwUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/game/new': typeof GameNewRoute
  '/api/awbw/map/$mapId': typeof ApiAwbwMapMapIdRoute
  '/api/awbw/user/$userId': typeof ApiAwbwUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/game/new'
    | '/api/awbw/map/$mapId'
    | '/api/awbw/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/game/new'
    | '/api/awbw/map/$mapId'
    | '/api/awbw/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/game/new'
    | '/api/awbw/map/$mapId'
    | '/api/awbw/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  GameNewRoute: typeof GameNewRoute
  ApiAwbwMapMapIdRoute: typeof ApiAwbwMapMapIdRoute
  ApiAwbwUserUserIdRoute: typeof ApiAwbwUserUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/new': {
      id: '/game/new'
      path: '/game/new'
      fullPath: '/game/new'
      preLoaderRoute: typeof GameNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/awbw/user/$userId': {
      id: '/api/awbw/user/$userId'
      path: '/api/awbw/user/$userId'
      fullPath: '/api/awbw/user/$userId'
      preLoaderRoute: typeof ApiAwbwUserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/awbw/map/$mapId': {
      id: '/api/awbw/map/$mapId'
      path: '/api/awbw/map/$mapId'
      fullPath: '/api/awbw/map/$mapId'
      preLoaderRoute: typeof ApiAwbwMapMapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  GameNewRoute: GameNewRoute,
  ApiAwbwMapMapIdRoute: ApiAwbwMapMapIdRoute,
  ApiAwbwUserUserIdRoute: ApiAwbwUserUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
