[package]
name = "awvm-awbw"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
awbrn-map.path = "../awbrn-map"
awbrn-types.path = "../awbrn-types"
awbw-replay.path = "../awbw-replay"
awvm.path = "../awvm"
indexmap.workspace = true
thiserror.workspace = true

[dev-dependencies]
highway.workspace = true
insta.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
